apiVersion: v1
kind: Pod
metadata:
  name: tomcat
  labels: 
    app: web
spec:
  containers:
    - name: tomcat
      image: tomcat
      ports:
        - containerPort: 8080
          hostPort: 8080
